services:
    database:
        image: mariadb:11.4
        container_name: clean_architecture_demo_database
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: admin # Change this password before deploying to production.
            MARIADB_DATABASE: CleanArchitectureDemoDb
            MARIADB_USER: admin
            MARIADB_PASSWORD: admin # Change this password before deploying to production.
        volumes:
            - clean_architecture_demo_data:/var/lib/mysql
        healthcheck:
            test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
            interval: 3s
            timeout: 3s
            retries: 5
        networks:
            - backend
        ports:
            - "3307:3306"

    keycloak:
        image: quay.io/keycloak/keycloak:latest
        container_name: keycloak_dev
        command: start-dev
        environment:
            - KC_BOOTSTRAP_ADMIN_USERNAME=admin
            - KC_BOOTSTRAP_ADMIN_PASSWORD=admin # these credentials are for development purposes only, change them before deploying to production.
        networks:
            - backend
        ports:
            - "8888:8080"

volumes:
    clean_architecture_demo_data:
        name: clean_architecture_demo_data

networks:
    backend:
        name: backend
        driver: bridge
